from time import sleep
from os import system

def calcperc():
    system('@echo off')
    system('cls')
    print("CALCULATRICE DE POURCENTAGE")
    sleep(1.5)
    print("Ce logiciel peut calculer un pourcentage\nou calculer une valeur moins un pourcentage et vice-versa résultat")
    print("Quelle action voulez-vous effectuer ?")
    print("1. Calculer un pourcentage")
    print("2. Calculer une valeur moins un pourcentage")
    print("3. Calculer une valeur plus un pourcentage")
    print("0. Quitter")
    answer = int(input("==>  "))
    if answer == 1:
        calcpercentage()
    elif answer == 2:
        percmoins()
    elif answer == 3:
        percplus()
    elif answer == 0:
        print("Vous allez quitter le logiciel dans 5 secondes...")
        sleep(2.7)
        print("Vous quittez le logiciel...")
        sleep(1.8)
        system('cls')
        sleep(1)
        exit("Exit...")
    elif answer != 1 or 2 or 3 or 0:
        print("Veuillez entrer 1 pour commencer! Pour Quitter, taper 0.")
        sleep(2)
        calcperc()

def calcpercentage():
    sleep(1.2)
    system('@echo off')
    system('cls')
    print("Calculateur de pourcentage\n".upper())
    sleep(1)
    print("EXEMPLE")
    print('\x1B[3m',"20% de 80", '\x1B[0m')
    print('\x1B[3m',"Entrez un pourcentage = 20", '\x1B[0m')
    print('\x1B[3m',"Entrez une valeur = 80", '\x1B[0m')
    print('\x1B[3m','Voici à quoi correspond 20% de 80 : 16','\x1B[0m\n')
    sleep(1)
    print("Entrez un pourcentage")
    perc = float(input("==>  "))
    print("Entrez une valeur")
    value = float(input("==>  "))
    calcul = (value*perc)/100
    print(f"Voici à quoi correspond {perc}% de {value} : {calcul}")
    sleep(2)
    system('pause')
    print('Accueil...')
    sleep(1.2)
    calcperc()

def percmoins():
    sleep(1.2)
    system('@echo off')
    system('cls')
    print("Calculateur de réduction avec un pourcentage\n".upper())
    sleep(1)
    print("EXEMPLE")
    print('\x1B[3m',"80 - 20%", '\x1B[0m')
    print('\x1B[3m',"Entrez un pourcentage = 20", '\x1B[0m')
    print('\x1B[3m',"Entrez une valeur = 80", '\x1B[0m')
    print('\x1B[3m','Voici à quoi correspond 80 - 20% = 64','\x1B[0m\n')
    sleep(1)
    print("Entrez un pourcentage (sans le -)")
    perc = float(input("==>  "))
    print("Entrez une valeur")
    value = float(input("==>  "))
    calcul = value - value * (perc / 100)
    print(f"Voici à quoi correspond {value} - {perc}% : {round(calcul, ndigits=2)}")
    sleep(2)
    system('pause')
    print('Accueil...')
    sleep(1.2)
    calcperc()

def percplus():
    sleep(1.2)
    system('@echo off')
    system('cls')
    print("Calculateur d'augmentation avec un pourcentage\n".upper())
    sleep(1)
    print("EXEMPLE")
    print('\x1B[3m',"80 + 20%", '\x1B[0m')
    print('\x1B[3m',"Entrez un pourcentage = 20", '\x1B[0m')
    print('\x1B[3m',"Entrez une valeur = 80", '\x1B[0m')
    print('\x1B[3m','Voici à quoi correspond 80 + 20% = 96','\x1B[0m\n')
    sleep(1)
    print("Entrez un pourcentage (sans le +)")
    perc = float(input("==>  "))
    print("Entrez une valeur")
    value = float(input("==>  "))
    calcul = value + value * (perc / 100)
    print(f"Voici à quoi correspond {value} + {perc}% : {round(calcul, ndigits=2)}")
    sleep(2)
    system('pause')
    print('Accueil...')
    sleep(1.2)
    calcperc()